[db]
host = 'localhost'
port = 27017
name = 'Alab'
username = ''
password = ''

[devices]
device_dir = "devices"
device_db = "devices"

[tasks]
task_dir = "tasks"
task_db = "tasks"

[sample_positions]
sample_db = "sample_positions"