[general]
name = 'default_lab'
working_dir = "."

[mongodb]
host = 'localhost'
password = ''
port = 27017
username = ''

[mongodb_completed]
host = "localhost"
password = ""
port = 27017
username = ""

[rabbitmq]
host = "localhost"
port = 5672
