[general]
definition_dir = "."
containers = ["crucible", "flask", "vial"]

[db]
host = 'localhost'
port = 27017
name = 'Alab'
username = ''
password = ''

[devices]
device_db = "devices"

[tasks]
task_definition_db = "task_definitions"

[sample_positions]
sample_position_db = "sample_positions"
sample_db = "samples"
