[general]
working_dir = "."
containers = ["crucible", "flask", "vial"]

[db]
host = 'localhost'
port = 27017
name = 'Alab'
username = ''
password = ''

[devices]
device_db = "devices"

[tasks]
task_db = "tasks"

[sample_positions]
sample_db = "samples"
