- name: "Synthesis of LiCoO2"
- samples:
  - default_sample
- tasks:
  - type: add_solid
    samples:
      - sample: default_sample
    parameters:
      - precursors:
        - name: Li2CO3
          amount: 2.45
          unit: g
        - name: Co2O3
          amount: 3.2
          unit: g
  - type: add_liquid
    parameters:
      - precursors:
        - name: ethanol
          amount: 5
          unit: ml
  - type: ball-milling
    samples:
      - sample: default_sample
    parameters:
      - time: 12
        unit: h
      - speed: 250
      - run: 30
        unit: min
      - interval: 5
        unit: min
  - type: firing
    samples:
      - sample: default_sample
    parameters:
      - set_points:
        - (2, 900)
        - (12, 900)
        - (0, 0)
  - type: xrd
    samples:
      - sample: default_sample
    parameters:
      degree_min: 20
      degree_high: 80
      d_theta: 0.02
