name: Format code using Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: psf/black@stable
      #   with:
      #     src: "./alab_management"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7  # Specify the Python version you need
      - name: Install Black
        run: pip install black==22.3.0
      - name: Run Black
        run: black ./alab_management
