name: CI

on:
  push:
    branches:
      - master

jobs:
  py3test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 4.4
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up environment
        run: |
          pip install --quiet -r ./requirements.txt -r ./requirements-dev.txt
          pip install --quiet .
      - name: Pytest
        run: pytest
      - name: Pyright
        uses: jakebailey/pyright-action@v1
        with:
          working-directory: alab_management/
          lib: true
      - name: Flake8
        run: flake8 alab_management
      - name: Pylint
        run: pylint alab_management
