name: Pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:
    branches:
      - sphinx-docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Set up dependencies
        run: pip install -r ./requirements.txt -r ./requirements-dev.txt
      - name: Compile sphinx
        working-directory: ./docs
        run: make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: sphinx-docs
